import { MonsterLocal } from "../app/models";
import { EquipmentTree } from "../app/shared/enums";

export const MONSTER_TABLE: MonsterLocal[] = [
  {
    id: 0,
    name: EquipmentTree.greatJagras,
    description: "Great Jagras is an opportunistic predator known for its insatiable appetite. Sporting a distinctive expandable gullet, Great Jagras swallows prey whole, making it a formidable yet relatively low-tier monster.",
    materials: [14, 20, 21, 41, 42, 43, 44],
    gathering: [
      { materials: [15, 43], entry: 2 },
      { materials: [16, 21], entry: 5 },
      { materials: [1, 3, 11], entry: 7 },
      { materials: [1, 3, 9], entry: 8 },
      { materials: [0, 2], entry: 10 },
      { materials: [43, 44], entry: 14 },
      { materials: [0, 2], entry: 16 },
      { materials: [41, 42], entry: 17 },
      { materials: [10, 14, 15], entry: 21 },
      { materials: [18, 21], entry: 22 },
      { materials: [0, 2], entry: 23 },
      { materials: [16, 41], entry: 25 },
      { materials: [17], entry: 26 },
      { materials: [20], entry: 27 },
      { materials: [3], entry: 28 },
      { materials: [11], entry: 29 }
    ],
    weapons: [6, 7],
    armours: [3]
  },
  {
    id: 1,
    name: EquipmentTree.barroth,
    description: "Barroth is a large, mud-covered monster that thrives in arid environments. It uses its tough, mud-encrusted hide to protect itself from attacks and can create mudslides to hinder hunters.",
    materials: [14, 55, 56, 57, 58],
    gathering: [
      { materials: [15, 58], entry: 2 },
      { materials: [16, 58], entry: 5 },
      { materials: [57], entry: 6 },
      { materials: [59], entry: 7 },
      { materials: [0, 1], entry: 8 },
      { materials: [55, 57], entry: 9 },
      { materials: [59], entry: 10 },
      { materials: [16, 55], entry: 11 },
      { materials: [0, 1], entry: 13 },
      { materials: [11], entry: 15 },
      { materials: [10, 14, 15], entry: 17 },
      { materials: [57, 58], entry: 18 },
      { materials: [17], entry: 20 },
      { materials: [55, 56], entry: 24 },
      { materials: [18, 56], entry: 26 },
      { materials: [1, 3, 9], entry: 27 },
      { materials: [1, 3, 11], entry: 28 }
    ],
    weapons: [8, 9],
    armours: [4]
  },
  {
    id: 2,
    name: EquipmentTree.kuluYaKu,
    description: "Kulu-Ya-Ku is a bird-like monster known for its unique ability to pick up and use objects as shields or weapons. It is often seen in the Ancient Forest, where it forages for eggs and other items.",
    materials: [4, 12, 45, 46, 47, 48],
    gathering: [
      { materials: [0, 2, 14], entry: 1 },
      { materials: [47, 48], entry: 2 },
      { materials: [46], entry: 3 },
      { materials: [45, 46], entry: 4 },
      { materials: [47], entry: 6 },
      { materials: [6], entry: 8 },
      { materials: [48], entry: 9 },
      { materials: [11], entry: 12 },
      { materials: [45], entry: 13 },
      { materials: [10, 15], entry: 14 },
      { materials: [4, 10], entry: 16 },
      { materials: [33], entry: 17 },
      { materials: [48], entry: 18 },
      { materials: [33], entry: 19 },
      { materials: [48], entry: 20 },
      { materials: [1, 17], entry: 21 },
      { materials: [47], entry: 22 },
      { materials: [45], entry: 23 },
      { materials: [33], entry: 25 },
      { materials: [4, 33], entry: 26 },
      { materials: [3], entry: 27 },
      { materials: [12, 48], entry: 28 },
      { materials: [4], entry: 29 }
    ],
    weapons: [10, 11],
    armours: [5]
  },
  {
    id: 3,
    name: EquipmentTree.tobiKadachi,
    description: "Tobi-Kadachi is a nimble, squirrel-like monster that can generate electricity. It is known for its agility and ability to leap between trees, making it a challenging opponent in the forest.",
    materials: [15, 17, 31, 32, 65, 66, 67, 68, 69],
    gathering: [
      { materials: [1, 6], entry: 1 },
      { materials: [66], entry: 2 },
      { materials: [14, 18], entry: 3 },
      { materials: [5, 11, 36], entry: 4 },
      { materials: [67], entry: 5 },
      { materials: [1, 5, 6], entry: 6 },
      { materials: [69], entry: 7 },
      { materials: [14, 16, 31, 32, 65, 68], entry: 8 },
      { materials: [17], entry: 9 },
      { materials: [10, 16], entry: 11 },
      { materials: [0, 2, 3, 9], entry: 12 },
      { materials: [65], entry: 13 },
      { materials: [14], entry: 15 },
      { materials: [12, 18], entry: 16 },
      { materials: [12], entry: 17 },
      { materials: [38], entry: 19 },
      { materials: [11, 38], entry: 21 },
      { materials: [6, 9, 31], entry: 22 },
      { materials: [10, 14], entry: 23 },
      { materials: [10, 11, 12], entry: 25 },
      { materials: [0, 1, 2, 3], entry: 29 },
      { materials: [36, 69], entry: 30 }
    ],
    weapons: [12, 13],
    armours: [6]
  },
  {
    id: 4,
    name: EquipmentTree.pukeiPukei,
    description: "Pukei-Pukei is a bird-like monster that can spit poison and has a vibrant, colorful appearance. It is often found in lush environments and uses its long tongue to catch prey.",
    materials: [15, 22, 23, 49, 50, 51, 52, 53, 54],
    gathering: [
      { materials: [1, 6], entry: 1 },
      { materials: [49], entry: 2 },
      { materials: [14, 18], entry: 3 },
      { materials: [11, 53], entry: 4 },
      { materials: [52], entry: 5 },
      { materials: [22, 51, 53], entry: 7 },
      { materials: [51], entry: 8 },
      { materials: [10, 16], entry: 10 },
      { materials: [49], entry: 11 },
      { materials: [48], entry: 13 },
      { materials: [14], entry: 14 },
      { materials: [0, 1, 2, 3], entry: 15 },
      { materials: [1, 5, 22], entry: 16 },
      { materials: [11], entry: 17 },
      { materials: [52], entry: 18 },
      { materials: [23], entry: 22 },
      { materials: [53], entry: 23 },
      { materials: [14], entry: 25 },
      { materials: [53], entry: 28 },
      { materials: [12, 18], entry: 29 },
      { materials: [14, 16], entry: 30 },
      { materials: [10, 11, 12], entry: 32 },
      { materials: [0, 2, 3, 53], entry: 33 }
    ],
    weapons: [14, 15],
    armours: [7]
  },
  {
    id: 5,
    name: EquipmentTree.tzitziYaKu,
    description: "Tzitzi-Ya-Ku is a bird-like monster known for its ability to emit a blinding flash of light. This unique defense mechanism allows it to disorient hunters and escape from danger.",
    materials: [75, 76, 77, 78],
    gathering: [
      { materials: [1], entry: 1 },
      { materials: [12, 14, 75], entry: 2 },
      { materials: [5, 7, 76], entry: 3 },
      { materials: [5, 12, 77, 78], entry: 4 },
      { materials: [0, 12, 78], entry: 5 },
      { materials: [5, 6], entry: 6 },
      { materials: [1, 5, 11], entry: 7 },
      { materials: [10, 14], entry: 12 },
      { materials: [14, 75], entry: 14 },
      { materials: [0, 6, 77], entry: 16 },
      { materials: [3, 18], entry: 17 },
      { materials: [11], entry: 18 },
      { materials: [5, 6, 10, 77], entry: 19 },
      { materials: [2, 75], entry: 20 },
      { materials: [2, 10, 14], entry: 21 },
      { materials: [12], entry: 22 },
      { materials: [7, 15, 76], entry: 23 },
      { materials: [75], entry: 24 },
      { materials: [3], entry: 25 },
      { materials: [75, 76], entry: 26 },
      { materials: [76, 77], entry: 27 },
      { materials: [0, 3, 17], entry: 29 },
      { materials: [7], entry: 30 },
      { materials: [2, 3, 5], entry: 31 }
    ],
    weapons: [16, 17],
    armours: [8]
  },
  {
    id: 6,
    name: EquipmentTree.greatGirros,
    description: "Great Girros is a large, snake-like monster that can emit a powerful electric shock. It is often found in the Rotten Vale, where it uses its electric attacks to stun prey and defend itself.",
    materials: [79, 80, 81, 82],
    gathering: [
      { materials: [14, 40], entry: 1 },
      { materials: [3, 14, 15, 79], entry: 2 },
      { materials: [3, 24, 79, 81], entry: 3 },
      { materials: [24, 39, 40, 82], entry: 4 },
      { materials: [24, 80], entry: 5 },
      { materials: [2, 3, 16], entry: 7 },
      { materials: [1, 6], entry: 9 },
      { materials: [40], entry: 11 },
      { materials: [3, 10, 14, 15, 16], entry: 12 },
      { materials: [10, 14], entry: 15 },
      { materials: [0, 2], entry: 16 },
      { materials: [24, 39, 40], entry: 18 },
      { materials: [39, 40, 79], entry: 19 },
      { materials: [24], entry: 20 },
      { materials: [39], entry: 21 },
      { materials: [0, 10], entry: 22 },
      { materials: [3, 10, 14, 15], entry: 23 },
      { materials: [79, 81], entry: 24 },
      { materials: [6, 11, 12, 18], entry: 25 },
      { materials: [15], entry: 28 },
      { materials: [80], entry: 29 },
      { materials: [81, 82], entry: 31 }
    ],
    weapons: [18, 19],
    armours: [9]
  },
  {
    id: 7,
    name: EquipmentTree.anjanath,
    description: "Anjanath is a large, dinosaur-like monster known for its fiery breath and aggressive nature. It is often found in the Ancient Forest, where it preys on smaller monsters and defends its territory fiercely.",
    materials: [16, 17, 70, 71, 72, 73, 74],
    gathering: [
      { materials: [18], entry: 1 },
      { materials: [10, 17, 72], entry: 2 },
      { materials: [18], entry: 3 },
      { materials: [74], entry: 4 },
      { materials: [73, 74], entry: 5 },
      { materials: [72], entry: 6 },
      { materials: [10, 17], entry: 12 },
      { materials: [1, 3], entry: 16 },
      { materials: [71, 72], entry: 18 },
      { materials: [5, 6], entry: 20 },
      { materials: [12, 36, 72], entry: 21 },
      { materials: [16, 27], entry: 22 },
      { materials: [9, 38], entry: 25 }
    ],
    weapons: [20, 21],
    armours: [10]
  },
  {
    id: 8,
    name: EquipmentTree.jyuratodus,
    description: "Jyuratodus is a large, mud-covered monster that inhabits wetlands. It uses its mud-covered body to blend into its surroundings and can create mudslides to hinder hunters. Its attacks are often slow but powerful.",
    materials: [16, 29, 37, 60, 61, 62, 63, 64],
    gathering: [
      { materials: [18], entry: 1 },
      { materials: [17, 10, 64], entry: 2 },
      { materials: [18], entry: 3 },
      { materials: [62], entry: 4 },
      { materials: [29, 64], entry: 5 },
      { materials: [1, 3], entry: 10 },
      { materials: [61, 62], entry: 15 },
      { materials: [34], entry: 16 },
      { materials: [12, 30, 60], entry: 22 },
      { materials: [60], entry: 23 },
      { materials: [16, 29], entry: 24 },
      { materials: [1, 30], entry: 26 },
      { materials: [10, 17], entry: 27 }
    ],
    weapons: [22, 23],
    armours: [12]
  },
  {
    id: 9,
    name: EquipmentTree.radobaan,
    description: "Radobaan is a rolling, boulder-like monster that can use its body to crush prey. It is often found in rocky areas and can create shockwaves by rolling into the ground, making it a unique and challenging opponent.",
    materials: [25, 26, 83, 84, 85, 86],
    gathering: [
      { materials: [10, 18], entry: 1 },
      { materials: [25, 83, 86], entry: 2 },
      { materials: [84], entry: 3 },
      { materials: [85], entry: 4 },
      { materials: [17], entry: 5 },
      { materials: [11], entry: 6 },
      { materials: [16], entry: 7 },
      { materials: [2, 3, 10, 12], entry: 9 },
      { materials: [0, 6, 83, 84], entry: 10 },
      { materials: [2, 3, 17], entry: 11 },
      { materials: [1, 6, 84, 86], entry: 12 },
      { materials: [17], entry: 14 },
      { materials: [25], entry: 15 },
      { materials: [0], entry: 16 },
      { materials: [10, 12, 17], entry: 17 },
      { materials: [83, 86], entry: 18 },
      { materials: [25], entry: 19 },
      { materials: [17, 83], entry: 20 },
      { materials: [2], entry: 21 },
      { materials: [16], entry: 22 },
      { materials: [0, 3], entry: 25 },
      { materials: [1, 3, 16], entry: 26 },
      { materials: [6], entry: 29 },
      { materials: [6, 12], entry: 30 },
      { materials: [2, 4, 10], entry: 31 }
    ],
    weapons: [24, 25],
    armours: [12]
  },
  {
    id: 10,
    name: EquipmentTree.rathalos,
    description: "Rathalos, the King of the Skies, is a fearsome wyvern known for its aerial prowess and deadly fire attacks. It is a symbol of power in the Monster Hunter world and is revered by hunters for its challenging battles.",
    materials: [16, 28, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96],
    gathering: [
      { materials: [11], entry: 1 },
      { materials: [28], entry: 2 },
      { materials: [91, 95], entry: 3 },
      { materials: [92], entry: 4 },
      { materials: [28, 36], entry: 5 },
      { materials: [89], entry: 6 },
      { materials: [10, 14], entry: 8 },
      { materials: [3], entry: 9 },
      { materials: [38], entry: 10 },
      { materials: [2], entry: 11 },
      { materials: [92], entry: 12 },
      { materials: [94], entry: 13 },
      { materials: [5, 36, 88], entry: 17 },
      { materials: [92], entry: 23 },
      { materials: [90], entry: 25 },
      { materials: [0], entry: 27 },
      { materials: [12], entry: 28 },
      { materials: [6, 93], entry: 30 },
      { materials: [1, 9, 88], entry: 31 }
    ],
    weapons: [26, 27],
    armours: [13]
  },
  {
    id: 11,
    name: EquipmentTree.rathalosAzure,
    description: "Azure Rathalos is a variant of the classic Rathalos, known for its icy breath and blue scales. It is a formidable opponent that combines the aerial agility of Rathalos with the chilling effects of ice.",
    materials: [16, 28, 97, 98, 99, 100, 101, 102, 103],
    gathering: [
      { materials: [11], entry: 1 },
      { materials: [28], entry: 2 },
      { materials: [98, 101], entry: 3 },
      { materials: [99], entry: 4 },
      { materials: [28, 36], entry: 5 },
      { materials: [102], entry: 7 },
      { materials: [99], entry: 9 },
      { materials: [97], entry: 11 },
      { materials: [99], entry: 12 },
      { materials: [0], entry: 14 },
      { materials: [3], entry: 20 },
      { materials: [12], entry: 21 },
      { materials: [102], entry: 22 },
      { materials: [2, 100], entry: 24 },
      { materials: [6, 101], entry: 25 },
      { materials: [1, 9, 98], entry: 27 },
      { materials: [38], entry: 28 },
      { materials: [5, 36, 97], entry: 29 },
      { materials: [10, 14], entry: 30 }
    ],
    weapons: [28, 29],
    armours: [14]
  },
  {
    id: 12,
    name: EquipmentTree.diablos,
    description: "Diablos is a massive, horned wyvern known for its burrowing abilities and aggressive nature. It is often found in desert regions, where it uses its horns to dig and ambush unsuspecting prey.",
    materials: [104, 105, 106, 107, 108, 109, 110],
    gathering: [
      { materials: [11], entry: 1 },
      { materials: [34], entry: 2 },
      { materials: [105, 109], entry: 3 },
      { materials: [104], entry: 4 },
      { materials: [105, 106], entry: 5 },
      { materials: [1, 7, 34], entry: 6 },
      { materials: [108], entry: 9 },
      { materials: [104], entry: 11 },
      { materials: [0], entry: 15 },
      { materials: [12], entry: 16 },
      { materials: [106], entry: 17 },
      { materials: [3], entry: 19 },
      { materials: [34], entry: 20 },
      { materials: [108], entry: 22 },
      { materials: [7], entry: 25 },
      { materials: [107], entry: 26 },
      { materials: [7, 104], entry: 27 },
      { materials: [10, 14], entry: 28 },
      { materials: [6, 107], entry: 29 },
      { materials: [2], entry: 30 }
    ],
    weapons: [30, 31],
    armours: [15]
  },
  {
    id: 13,
    name: EquipmentTree.diablosBlack,
    description: "Black Diablos is a more aggressive and territorial variant of Diablos, known for its black scales and increased ferocity. It is a formidable opponent that poses a significant threat to hunters in its territory.",
    materials: [8, 34, 109, 110, 111, 112, 113],
    gathering: [
      { materials: [11], entry: 1 },
      { materials: [8], entry: 2 },
      { materials: [8, 109], entry: 3 },
      { materials: [109], entry: 4 },
      { materials: [8, 34], entry: 5 },
      { materials: [1, 8, 34], entry: 9 },
      { materials: [0], entry: 11 },
      { materials: [3], entry: 15 },
      { materials: [12], entry: 16 },
      { materials: [111, 112], entry: 17 },
      { materials: [109], entry: 19 },
      { materials: [2, 113], entry: 20 },
      { materials: [112], entry: 21 },
      { materials: [6, 34], entry: 23 },
      { materials: [111], entry: 24 },
      { materials: [111], entry: 26 },
      { materials: [14], entry: 27 },
      { materials: [8], entry: 28 },
      { materials: [34, 112, 113], entry: 30 }
    ],
    weapons: [32, 33],
    armours: [16]
  },
  {
    id: 14,
    name: EquipmentTree.kushalaDaora,
    description: "Kushala Daora is an Elder Dragon known for its metallic scales and ability to control wind. It is a powerful and elusive monster that poses a significant challenge to hunters, often found in stormy regions.",
    materials: [19, 35, 135, 136, 137, 138, 139, 140, 141],
    gathering: [
      { materials: [91], entry: 1 },
      { materials: [137, 140], entry: 3 },
      { materials: [120, 141], entry: 4 },
      { materials: [35], entry: 5 },
      { materials: [110], entry: 6 },
      { materials: [137], entry: 7 },
      { materials: [19], entry: 8 },
      { materials: [135], entry: 10 },
      { materials: [139], entry: 11 },
      { materials: [136], entry: 12 },
      { materials: [135], entry: 13 },
      { materials: [140], entry: 14 },
      { materials: [138], entry: 18 },
      { materials: [137], entry: 19 },
      { materials: [106], entry: 20 },
      { materials: [136], entry: 24 },
      { materials: [87], entry: 25 },
      { materials: [35], entry: 26 },
      { materials: [19], entry: 27 },
      { materials: [89, 109], entry: 29 },
      { materials: [35], entry: 31 },
      { materials: [105, 135], entry: 32 },
      { materials: [141], entry: 34 },
      { materials: [94], entry: 36 },
      { materials: [120], entry: 37 }
    ],
    weapons: [34, 35],
    armours: [17]
  },
  {
    id: 15,
    name: EquipmentTree.teostra,
    description: "Teostra is a fiery Elder Dragon known for its explosive attacks and mastery of fire. It is a formidable opponent that can create devastating firestorms, making it one of the most dangerous monsters in the game.",
    materials: [8, 9, 126, 127, 128, 129, 130, 131, 132, 133, 134],
    gathering: [
      { materials: [129], entry: 3 },
      { materials: [130, 134], entry: 4 },
      { materials: [126, 128], entry: 5 },
      { materials: [133], entry: 8 },
      { materials: [106], entry: 9 },
      { materials: [34], entry: 11 },
      { materials: [95], entry: 12 },
      { materials: [129], entry: 13 },
      { materials: [126], entry: 16 },
      { materials: [133], entry: 17 },
      { materials: [105], entry: 18 },
      { materials: [133], entry: 19 },
      { materials: [130], entry: 21 },
      { materials: [127], entry: 22 },
      { materials: [128], entry: 23 },
      { materials: [91], entry: 27 },
      { materials: [34], entry: 28 },
      { materials: [8], entry: 29 },
      { materials: [89, 132], entry: 30 },
      { materials: [109], entry: 33 },
      { materials: [134], entry: 34 },
      { materials: [9], entry: 35 },
      { materials: [87, 131], entry: 36 },
      { materials: [134], entry: 37 }
    ],
    weapons: [36, 37],
    armours: [18]
  },
  {
    id: 16,
    name: EquipmentTree.nergigante,
    description: "Nergigante is a terrifying Elder Dragon known for its regenerative abilities and aggressive behavior. It is a formidable opponent that poses a significant threat to both hunters and the ecosystem.",
    materials: [19, 35, 119, 120, 121, 122, 123, 124, 125],
    gathering: [
      { materials: [119, 125], entry: 4 },
      { materials: [19, 35], entry: 5 },
      { materials: [35], entry: 6 },
      { materials: [95], entry: 9 },
      { materials: [35], entry: 10 },
      { materials: [110], entry: 11 },
      { materials: [19], entry: 14 },
      { materials: [120], entry: 15 },
      { materials: [125], entry: 16 },
      { materials: [119], entry: 17 },
      { materials: [121], entry: 20 },
      { materials: [122], entry: 23 },
      { materials: [106], entry: 25 },
      { materials: [91], entry: 26 },
      { materials: [120], entry: 27 },
      { materials: [124], entry: 28 },
      { materials: [89, 109], entry: 30 },
      { materials: [123], entry: 34 },
      { materials: [122], entry: 35 },
      { materials: [105], entry: 37 },
      { materials: [87], entry: 38 }
    ],
    weapons: [38, 39],
    armours: [19]
  },
  {
    id: 17,
    name: EquipmentTree.kirin,
    description: "Kirin is a mythical creature resembling a unicorn, known for its lightning-fast speed and electrical attacks. It is a rare sight in the Monster Hunter world, often appearing during thunderstorms.",
    materials: [114, 115, 116, 117, 118],
    gathering: [
      { materials: [6], entry: 1 },
      { materials: [7], entry: 2 },
      { materials: [115], entry: 3 },
      { materials: [118], entry: 4 },
      { materials: [13, 118], entry: 5 },
      { materials: [6], entry: 7 },
      { materials: [114], entry: 8 },
      { materials: [7, 13], entry: 9 },
      { materials: [91, 115], entry: 10 },
      { materials: [110], entry: 11 },
      { materials: [116], entry: 14 },
      { materials: [13], entry: 15 },
      { materials: [6], entry: 17 },
      { materials: [13, 117], entry: 18 },
      { materials: [91, 95, 110], entry: 19 },
      { materials: [7], entry: 20 },
      { materials: [13, 114], entry: 21 },
      { materials: [6], entry: 22 },
      { materials: [13, 87], entry: 23 },
      { materials: [106, 109], entry: 24 },
      { materials: [110], entry: 26 },
      { materials: [116, 117], entry: 27 },
      { materials: [7, 117], entry: 28 },
      { materials: [89, 114], entry: 29 },
      { materials: [116, 117], entry: 30 },
      { materials: [1, 105, 106], entry: 31 },
      { materials: [89, 118], entry: 33 },
      { materials: [6, 115, 116, 117], entry: 34 },
      { materials: [115, 116], entry: 35 },
      { materials: [95], entry: 36 },
      { materials: [2], entry: 37 },
      { materials: [87, 105, 109], entry: 38 },
      { materials: [6, 13], entry: 40 },
      { materials: [114], entry: 41 },
      { materials: [0], entry: 42 },
      { materials: [7, 105], entry: 43 },
      { materials: [1, 2], entry: 44 },
      { materials: [106], entry: 45 },
      { materials: [109], entry: 46 }
    ],
    weapons: [40, 41],
    armours: [20]
  },
  {
    id: 18,
    name: EquipmentTree.barioth,
    description: "Barioth is a large, feline-like monster known for its icy breath and agility. It is often found in snowy regions, where it uses its speed and ice attacks to hunt prey and evade hunters.",
    materials: [],
    gathering: [],
    weapons: [],
    armours: []
  },
  {
    id: 19,
    name: EquipmentTree.rajang,
    description: "Rajang is a powerful, ape-like monster known for its incredible strength and lightning attacks. It is a formidable opponent that can enter a berserk state, increasing its speed and damage output significantly.",
    materials: [],
    gathering: [],
    weapons: [],
    armours: []
  }
];